Build: Docs: Pin RTD Sphinx version
- RTD updated from Sphinx v6.2.1 to Sphinx v7.2.6, and now build fails:

    sphinx.errors.ThemeError: An error happened in rendering the page authors.
    Reason: UndefinedError("'style' is undefined")